# Generated by Django 4.0.4 on 2023-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0002_po_so_luong_alter_hopdong_ma_nhan_vien_tao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='ma_hang_hoa',
            field=models.ManyToManyField(blank=True, to='web_core.hanghoa', verbose_name='Mã hàng hoá'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='trang_thai',
            field=models.CharField(choices=[('Đang xem xét', 'Đang xem xét'), ('Đã ký', 'Đã ký'), ('Đang có hiệu lực', 'Đang có hiệu lực'), ('Đã hết hạn', 'Đã hết hạn')], default='Đang xem xét', max_length=100, null=True, verbose_name='Trạng thái hợp đồng'),
        ),
        migrations.RemoveField(
            model_name='ncc',
            name='ma_hang_hoa',
        ),
        migrations.AddField(
            model_name='ncc',
            name='ma_hang_hoa',
            field=models.ManyToManyField(blank=True, to='web_core.hanghoa', verbose_name='Mã hàng hoá'),
        ),
        migrations.AlterField(
            model_name='po',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('Chờ phê duyệt', 'Chờ phê duyệt'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã nhận hàng', 'Đã nhận hàng'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Đang xem xét', max_length=100, null=True, verbose_name='Trạng thái PO'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ phân công', 'Chờ phân công'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Đang xem xét', max_length=100, null=True, verbose_name='Trạng thái PR'),
        ),
        migrations.AlterField(
            model_name='pr_hh',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ phân công', 'Chờ phân công'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], max_length=100, null=True, verbose_name='Trạng thái PR'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='trang_thai',
            field=models.CharField(choices=[('Đang chờ thanh toán', 'Đang chờ thanh toán'), ('Đã thanh toán lần 1', 'Đã thanh toán lần 1'), ('Đã hoàn thành', 'Đã hoàn thành')], max_length=100, verbose_name='Trạng thái thanh toán'),
        ),
    ]
