# Generated by Django 4.0.4 on 2023-04-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0003_alter_hopdong_ma_hang_hoa_remove_ncc_ma_hang_hoa_and_more'),
        ('web_core', '0004_alter_hopdong_ma_hang_hoa_alter_hopdong_trang_thai_and_more'),
    ]

    operations = [
    ]
