# Generated by Django 4.0.4 on 2023-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0005_merge_20230426_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='ma_hang_hoa',
            field=models.ManyToManyField(blank=True, to='web_core.hanghoa', verbose_name='Mã hàng hoá'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ phê duyệt', 'Chờ phê duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Đang có hiệu lực', 'Đang có hiệu lực'), ('Đã hết hạn', 'Đã hết hạn')], default='Đang xem xét', max_length=100, null=True, verbose_name='Trạng thái hợp đồng'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='ma_hang_hoa',
            field=models.ManyToManyField(blank=True, to='web_core.hanghoa', verbose_name='Mã hàng hoá'),
        ),
    ]
